// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ping-pong.proto
// Original file comments:
// バージョン 
#ifndef GRPC_ping_2dpong_2eproto__INCLUDED
#define GRPC_ping_2dpong_2eproto__INCLUDED

#include "ping-pong.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// パッケージ 
//
// インポート 
//
// サービス 
class PingPong final {
 public:
  static constexpr char const* service_full_name() {
    return "PingPong";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC 
    virtual ::grpc::Status SendPing(::grpc::ClientContext* context, const ::Ping& request, ::Pong* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Pong>> AsyncSendPing(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Pong>>(AsyncSendPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Pong>> PrepareAsyncSendPing(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Pong>>(PrepareAsyncSendPingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // RPC 
      virtual void SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Pong>* AsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Pong>* PrepareAsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendPing(::grpc::ClientContext* context, const ::Ping& request, ::Pong* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Pong>> AsyncSendPing(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Pong>>(AsyncSendPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Pong>> PrepareAsyncSendPing(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Pong>>(PrepareAsyncSendPingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, std::function<void(::grpc::Status)>) override;
      void SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Pong>* AsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Pong>* PrepareAsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendPing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC 
    virtual ::grpc::Status SendPing(::grpc::ServerContext* context, const ::Ping* request, ::Pong* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPing(::grpc::ServerContext* context, ::Ping* request, ::grpc::ServerAsyncResponseWriter< ::Pong>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendPing<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPing() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Ping, ::Pong>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Ping* request, ::Pong* response) { return this->SendPing(context, request, response); }));}
    void SetMessageAllocatorFor_SendPing(
        ::grpc::MessageAllocator< ::Ping, ::Pong>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Ping, ::Pong>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPing(
      ::grpc::CallbackServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendPing<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPing() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPing(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPing(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Ping, ::Pong>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Ping, ::Pong>* streamer) {
                       return this->StreamedSendPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::Ping* /*request*/, ::Pong* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Ping,::Pong>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendPing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendPing<Service > StreamedService;
};


#endif  // GRPC_ping_2dpong_2eproto__INCLUDED
