// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ping-pong.proto

#include "ping-pong.pb.h"
#include "ping-pong.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* PingPong_method_names[] = {
  "/PingPong/SendPing",
};

std::unique_ptr< PingPong::Stub> PingPong::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PingPong::Stub> stub(new PingPong::Stub(channel, options));
  return stub;
}

PingPong::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendPing_(PingPong_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PingPong::Stub::SendPing(::grpc::ClientContext* context, const ::Ping& request, ::Pong* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Ping, ::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendPing_, context, request, response);
}

void PingPong::Stub::async::SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Ping, ::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendPing_, context, request, response, std::move(f));
}

void PingPong::Stub::async::SendPing(::grpc::ClientContext* context, const ::Ping* request, ::Pong* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendPing_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Pong>* PingPong::Stub::PrepareAsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Pong, ::Ping, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendPing_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Pong>* PingPong::Stub::AsyncSendPingRaw(::grpc::ClientContext* context, const ::Ping& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

PingPong::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PingPong_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PingPong::Service, ::Ping, ::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PingPong::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Ping* req,
             ::Pong* resp) {
               return service->SendPing(ctx, req, resp);
             }, this)));
}

PingPong::Service::~Service() {
}

::grpc::Status PingPong::Service::SendPing(::grpc::ServerContext* context, const ::Ping* request, ::Pong* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


