// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: uid-manager.proto
// Original file comments:
// バージョン 
#ifndef GRPC_uid_2dmanager_2eproto__INCLUDED
#define GRPC_uid_2dmanager_2eproto__INCLUDED

#include "uid-manager.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// パッケージ 
//
// インポート 
//
// サービス 
class UidService final {
 public:
  static constexpr char const* service_full_name() {
    return "UidService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC 
    virtual ::grpc::Status GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::ResponseUidPool* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>> AsyncGetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>>(AsyncGetUidPoolRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>> PrepareAsyncGetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>>(PrepareAsyncGetUidPoolRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // RPC 
      virtual void GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>* AsyncGetUidPoolRaw(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResponseUidPool>* PrepareAsyncGetUidPoolRaw(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::ResponseUidPool* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>> AsyncGetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>>(AsyncGetUidPoolRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>> PrepareAsyncGetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>>(PrepareAsyncGetUidPoolRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response, std::function<void(::grpc::Status)>) override;
      void GetUidPool(::grpc::ClientContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>* AsyncGetUidPoolRaw(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ResponseUidPool>* PrepareAsyncGetUidPoolRaw(::grpc::ClientContext* context, const ::RequestUidPoolSize& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUidPool_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC 
    virtual ::grpc::Status GetUidPool(::grpc::ServerContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUidPool() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUidPool(::grpc::ServerContext* context, ::RequestUidPoolSize* request, ::grpc::ServerAsyncResponseWriter< ::ResponseUidPool>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUidPool<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUidPool() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RequestUidPoolSize, ::ResponseUidPool>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RequestUidPoolSize* request, ::ResponseUidPool* response) { return this->GetUidPool(context, request, response); }));}
    void SetMessageAllocatorFor_GetUidPool(
        ::grpc::MessageAllocator< ::RequestUidPoolSize, ::ResponseUidPool>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RequestUidPoolSize, ::ResponseUidPool>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUidPool(
      ::grpc::CallbackServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUidPool<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUidPool() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUidPool() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUidPool(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUidPool() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUidPool(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUidPool(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUidPool : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUidPool() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RequestUidPoolSize, ::ResponseUidPool>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RequestUidPoolSize, ::ResponseUidPool>* streamer) {
                       return this->StreamedGetUidPool(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUidPool() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUidPool(::grpc::ServerContext* /*context*/, const ::RequestUidPoolSize* /*request*/, ::ResponseUidPool* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUidPool(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RequestUidPoolSize,::ResponseUidPool>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUidPool<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUidPool<Service > StreamedService;
};


#endif  // GRPC_uid_2dmanager_2eproto__INCLUDED
